blank_issues_enabled: false
issue_templates:
  - name: 'Bug Report'
    description: 'Report a bug or unexpected behavior in the monorepo.'
    title: '[Bug] <Short Description>'
    labels: [bug]
    assignees: []
    template: bug_report.md
  - name: 'Feature Request'
    description: 'Request a new feature using the detailed template.'
    title: '[Feature] <Short Description>'
    labels: [feature, enhancement]
    assignees: []
    template: feature_request.md
  - name: 'Improvement/Refactor'
    description: 'Request an improvement or refactor in the monorepo.'
    title: '[Improvement] <Short Description>'
    labels: [enhancement, refactor]
    assignees: []
    template: improvement.md
  - name: 'Docs'
    description: 'Request or improve documentation in the monorepo.'
    title: '[Docs] <Short Description>'
    labels: [documentation]
    assignees: []
    template: documentation.md
  - name: 'Chore/Technical Task'
    description: 'Request a technical task or maintenance activity.'
    title: '[Chore] <Short Description>'
    labels: [chore]
    assignees: []
    template: chore.md
  - name: 'Security Issue'
    description: 'Report a security vulnerability or sensitive issue.'
    title: '[Security] <Short Description>'
    labels: [security]
    assignees: []
    template: security.md
