blank_issues_enabled: false
issue_templates:
  - name: 'Bug Report'
    description: 'Report a bug found in the monorepo.'
    title: '[Bug] <Short description>'
    labels: [bug]
    assignees: []
    template: bug_report.md
  - name: 'Feature Request'
    description: 'Request a new feature using the detailed template.'
    title: '[Feature] <Feature name>'
    labels: [feature, enhancement]
    assignees: []
    template: feature_request.md
  - name: 'Improvement/Refactor'
    description: 'Suggest an improvement or refactor.'
    title: '[Improvement] <Short description>'
    labels: [enhancement, refactor]
    assignees: []
    template: improvement.md
  - name: 'Documentation'
    description: 'Request or report documentation improvements.'
    title: '[Doc] <Short description>'
    labels: [documentation]
    assignees: []
    template: documentation.md
  - name: 'Chore/Technical Task'
    description: 'Request a technical task or maintenance.'
    title: '[Chore] <Short description>'
    labels: [chore]
    assignees: []
    template: chore.md
  - name: 'Security Issue'
    description: 'Report a security vulnerability.'
    title: '[Security] <Short description>'
    labels: [security]
    assignees: []
    template: security.md
