name: GitHub Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  setup-gh-secrets:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Configura secret GH_PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          if [ -z "$GH_PAT" ]; then
            echo "Secret GH_PAT não definido."
            exit 1
          fi
          echo "Configurando secret GH_PAT no repositório $GITHUB_REPO..."
          gh secret set GH_PAT --body "$GH_PAT" --repo "$GITHUB_REPO"
          echo "Secret GH_PAT configurado com sucesso!"

  protect-branches:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Protege branch main (apenas PRs)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          set -e
          echo '{
            "required_status_checks": {"strict": true, "contexts": []},
            "enforce_admins": true,
            "required_pull_request_reviews": {"required_approving_review_count": 0},
            "restrictions": null
          }' > branch-protection-main.json
          gh api -X PUT repos/$GITHUB_REPO/branches/main/protection --input branch-protection-main.json
          echo "Proteção aplicada à branch main: commits diretos bloqueados, apenas PRs!"
      - name: Protege branch dev (commits diretos permitidos)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          set -e
          echo '{
            "required_status_checks": {"strict": false, "contexts": []},
            "enforce_admins": false,
            "required_pull_request_reviews": null,
            "restrictions": null
          }' > branch-protection-dev.json
          gh api -X PUT repos/$GITHUB_REPO/branches/dev/protection --input branch-protection-dev.json
          echo "Proteção aplicada à branch dev: commits diretos permitidos!"
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Instala dependências para YAML
        run: pnpm add -w js-yaml axios
      - name: Sincroniza labels do GitHub
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "GH_PAT: $GH_PAT"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          export GITHUB_REPO="$GITHUB_REPOSITORY"
          node ./scripts/sync-labels.js
