name: Lint/Format Markdown e MDX

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - '.github/workflows/lint-mdx.yml'

jobs:
  lint-mdx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm exec prettier --write "**/*.{md,mdx}"
      - run: pnpm exec prettier --check "**/*.{md,mdx}"
