name: Update Internal Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'
  push:
    branches:
      - dev

jobs:
  update-internal-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica se o segredo GH_PAT está disponível
        run: |
          if [ -z "${{ secrets.GH_PAT }}" ]; then
            echo "ERRO: O segredo GH_PAT não está configurado nas Actions do repositório!" >&2
            exit 1
          else
            echo "GH_PAT está disponível."
          fi
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - name: Atualiza dependências internas
        run: pnpm update --latest --recursive
      - name: Lint
        run: pnpm lint
      - name: Testes
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Audit
        run: pnpm audit || true
      # O commit e push serão feitos automaticamente pelo create-pull-request
      # Não é necessário criar/pushar a branch manualmente
      - name: Verifica se há arquivos staged para commit após hooks
        id: check_staged
        run: |
          if git diff --cached --quiet; then
            echo "has_staged=false" >> $GITHUB_OUTPUT
          else
            echo "has_staged=true" >> $GITHUB_OUTPUT
          fi
      - name: Cria Pull Request automático
        if: steps.check_staged.outputs.has_staged == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: 'chore(deps-internal): atualiza dependências internas'
          branch: chore/update-internal-deps
          title: 'chore(deps-internal): atualiza dependências internas'
          body: 'Atualização automática das dependências internas do monorepo.'
      # -------------------------------------------------------------
      # Após atualizar dependências internas, sincroniza com o template (upstream)
      # Isso evita PRs redundantes de dependências caso o template e o filho atualizem juntos
      # O PR de sync só será criado se houver diferença estrutural real após atualizar as dependências
      # -------------------------------------------------------------
      - name: Sincroniza com upstream (template)
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'ArthurProjectCorrea/monorepo-starter'
          source_branch: 'main'
          destination_branch: 'main'
          github_token: ${{ secrets.GH_PAT }}
          sync_tags: 'true'
